name: Build and upload to PyPI

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.9", "3.12"]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools wheel
          python -m pip install '.[test]'

      - name: Package
        run: |
          python setup.py bdist_wheel

      - name: Archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.python-version }}
          path: |
              dist

  upload_pypi:
    name: Upload to PyPI
    runs-on: ubuntu-20.04
    needs: build
    environment:
      name: pypi
      url: https://pypi.org/project/cxxtea/
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist-${{ matrix.python-version }}
          path: dist

      - name: Upload to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}
